### PR TITLE
Added some optimization

### PR DESCRIPTION
**Pull request by mandar1jn**
In CommandEvent.java there were 2 if statements right after each other that were the same. And I **switched** some if statements to a switch statement (get it?)

### CODE REVIEW

**Review by Techie-Pi — APPROVED** [review]

**Comment by mandar1jn** [comment]
I love how this pull request has been up since 27 November and still hasn’t been merged/denied

**Comment by a-gt** [comment]
Lol

**Comment by kk5dire** [comment]
@mandar1jn 
> I love how this pull request has been up since 27 November and still hasn’t been merged/denied

lol i just read this cant you just ask someone who commits to the repo

**Comment by mandar1jn** [comment]
@kk5dire nope. He doesn’t check his github. @PolyMarsDev Here. I pinged him. I bet he won’t do anything with this for another 2 years. Around 2 months ago I exposed him in a Q&A. He promised to go check out his github repositories. Well, I have pull requests in almost all of his repositories and none have been merged or denied

**Comment by AffluentAvo** [comment]
I could merge them, however I do not maintain the public bots anymore and I am not sure what PolyMars would like to do with the code or if he would approve the merge. I will contact him to check this out.

**Comment by mandar1jn** [comment]
@AffluentAvo thanks!

**Comment by kk5dire** [comment]
@T0biii ?

**Comment by T0biii** [comment]
> @T0biii ?

yes?

**Comment by kk5dire** [comment]
> > @T0biii ?
> 
> yes?

oh I got confused by the random issue mention, for some reason I thought it meant you mentioned an issue here

**Comment by T0biii** [comment]
> > > @T0biii ?
> > 
> > 
> > yes?
> 
> oh I got confused by the random issue mention, for some reason I thought it meant you mentioned an issue here

in the Issue i mention this Pull Requests because of the erros he get.
Because one commit here fixed the encoding for the MYSQL PW

**Comment by mandar1jn** [comment]
> > > > @T0biii ?
> > > 
> > > 
> > > yes?
> > 
> > 
> > oh I got confused by the random issue mention, for some reason I thought it meant you mentioned an issue here
> 
> in the Issue i mention this Pull Requests because of the erros he get.
> Because one commit here fixed the encoding for the MYSQL PW

I fixed it not because it’s broken in the main repo, but because the program I used encoded it wrong.

**Pull request closed without merging**
